const data = {
  products: [
    {
      name: "Monitor 1",
      slug: "monitor1",
      category: "Monitor",
      image: "/images/Monitor1.webp",
      price: 70,
      rating: 4.5,
      countInStock: 20,
      description: "Un monitor muy facherito",
    },
    {
      name: "Monitor 2",
      slug: "monitor2",
      category: "Monitor",
      image: "/images/Monitoe2.webp",
      price: 80,
      rating: 3.2,
      countInStock: 20,
      description: "Monitor clase media",
    },
    {
      name: "Monitor 3",
      slug: "monitor3",
      category: "Monitor",
      image: "/images/Monitor.jpeg",
      price: 90,
      rating: 4.5,
      countInStock: 20,
      description: "Monitor clase baja",
    },
    {
      name: "Monitor 4",
      slug: "monitor4",
      category: "Monitor",
      image: "/images/Monitor3.webp",
      price: 90,
      rating: 2.9,
      countInStock: 20,
      description: "Monitor descente",
    },
    {
      name: "Monitor 5",
      slug: "monitor5",
      category: "Monitor",
      image: "/images/Monitor.jpeg",
      price: 95,
      rating: 3.5,
      countInStock: 20,
      description: "No es el mismo de la vez pasada",
    },
    {
      name: "Monitor 6",
      slug: "monitor6",
      category: "Monitor",
      image: "/images/Monitor3.webp",
      price: 75,
      rating: 2.4,
      countInStock: 20,
      description: "Te prometo que son otros",
    },
  ],
};

export default data